name: Sync and Deploy Blog

on:
  push:
    branches:
      - master
  repository_dispatch:
    types:
      - deploy
  workflow_dispatch:  # 支持手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"  # 兼容 16 和 16.x

      - name: Install Dependencies
        run: |
          export TZ='Asia/Shanghai'  # 保留时区设置
          npm install --production

      - name: Sync Notion Articles
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        run: npm run sync

      - name: Remove Articles in "修改中" Status
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        run: |
          node -e "
            const fs = require('fs').promises;
            const path = require('path');
            const { queryNotionDatabase } = require('@elog/cli/lib/utils/notion');
            (async () => {
              const articles = await queryNotionDatabase(process.env.NOTION_DATABASE_ID, process.env.NOTION_TOKEN);
              for (const article of articles.results) {
                const status = article.properties.status?.select?.name;
                if (status === '修改中') {
                  const fileName = article.properties.title + '.md';
                  const filePath = path.join('./source/_posts', fileName);
                  try {
                    await fs.unlink(filePath);
                    console.log('Deleted:', filePath);
                  } catch (err) {
                    console.log('File not found or error deleting:', filePath);
                  }
                }
              }
            })();
          "

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Pull Remote Changes
        run: |
          git pull origin master --rebase
        continue-on-error: true  # 如果没有远程更新，忽略错误

      - name: Commit Changes
        run: |
          echo `date +"%Y-%m-%d %H:%M:%S"` begin > time.txt  # 保留 time.txt
          git add .
          git commit -m "Sync Notion articles and remove '修改中' posts" || echo "No changes to commit"

      - name: Push Changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
